export const SET_SITE_THEME = 'SET_SITE_THEME'

export const AUTHENTICATE_USER_REQUEST = 'AUTHENTICATE_USER_REQUEST'
export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS'
export const AUTHENTICATE_USER_FAILURE = 'AUTHENTICATE_USER_FAILURE'
export const UPDATE_AUTH_CURRENT_USER = 'UPDATE_AUTH_CURRENT_USER'
export const STATUS_CURRENT_USER = 'STATUS_CURRENT_USER'

export const FORGOT_PASS_REQUEST = 'FORGOT_PASS_REQUEST'
export const FORGOT_PASS_SUCCESS = 'FORGOT_PASS_SUCCESS'
export const FORGOT_PASS_FAILURE = 'FORGOT_PASS_FAILURE'

export const CHECK_TOKEN_REQUEST = 'CHECK_TOKEN_REQUEST'
export const CHECK_TOKEN_SUCCESS = 'CHECK_TOKEN_SUCCESS'
export const CHECK_TOKEN_FAILURE = 'CHECK_TOKEN_FAILURE'

export const RESET_PASS_REQUEST = 'RESET_PASS_REQUEST'
export const RESET_PASS_SUCCESS = 'RESET_PASS_SUCCESS'
export const RESET_PASS_FAILURE = 'RESET_PASS_FAILURE'

// ACTION EMPLOYEE
export const LIST_EMPLOYEE_REQUEST = 'LIST_EMPLOYEE_REQUEST'
export const LIST_EMPLOYEE_SUCCESS = 'LIST_EMPLOYEE_SUCCESS'
export const LIST_EMPLOYEE_FAILURE = 'LIST_EMPLOYEE_FAILURE'

export const CREATE_EMPLOYEE_REQUEST = 'CREATE_EMPLOYEE_REQUEST'
export const CREATE_EMPLOYEE_SUCCESS = 'CREATE_EMPLOYEE_SUCCESS'
export const CREATE_EMPLOYEE_FAILURE = 'CREATE_EMPLOYEE_FAILURE'

export const UPDATE_EMPLOYEE_REQUEST = 'UPDATE_EMPLOYEE_REQUEST'
export const UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS'
export const UPDATE_EMPLOYEE_FAILURE = 'UPDATE_EMPLOYEE_FAILURE'

// ACTION SALARY
export const LIST_SALARY_REQUEST = 'LIST_SALARY_REQUEST'
export const LIST_SALARY_SUCCESS = 'LIST_SALARY_SUCCESS'
export const LIST_SALARY_FAILURE = 'LIST_SALARY_FAILURE'

export const DETAIL_SALARY_REQUEST = 'DETAIL_SALARY_REQUEST'
export const DETAIL_SALARY_SUCCESS = 'DETAIL_SALARY_SUCCESS'
export const DETAIL_SALARY_FAILURE = 'DETAIL_SALARY_FAILURE'

export const EXPORT_SALARY_REQUEST = 'EXPORT_SALARY_REQUEST'
export const EXPORT_SALARY_SUCCESS = 'EXPORT_SALARY_SUCCESS'
export const EXPORT_SALARY_FAILURE = 'EXPORT_SALARY_FAILURE'

// ACTION ABSENT
export const LIST_ABSENT_REQUEST = 'LIST_ABSENT_REQUEST'
export const LIST_ABSENT_SUCCESS = 'LIST_ABSENT_SUCCESS'
export const LIST_ABSENT_FAILURE = 'LIST_ABSENT_FAILURE'

export const CREATE_ABSENT_REQUEST = 'CREATE_ABSENT_REQUEST'
export const CREATE_ABSENT_SUCCESS = 'CREATE_ABSENT_SUCCESS'
export const CREATE_ABSENT_FAILURE = 'CREATE_ABSENT_FAILURE'

// ACTION DEDUCTION
export const LIST_DEDUCTION_REQUEST = 'LIST_DEDUCTION_REQUEST'
export const LIST_DEDUCTION_SUCCESS = 'LIST_DEDUCTION_SUCCESS'
export const LIST_DEDUCTION_FAILURE = 'LIST_DEDUCTION_FAILURE'

export const DETAIL_DEDUCTION_REQUEST = 'DETAIL_DEDUCTION_REQUEST'
export const DETAIL_DEDUCTION_SUCCESS = 'DETAIL_DEDUCTION_SUCCESS'
export const DETAIL_DEDUCTION_FAILURE = 'DETAIL_DEDUCTION_FAILURE'

export const CREATE_DEDUCTION_REQUEST = 'CREATE_DEDUCTION_REQUEST'
export const CREATE_DEDUCTION_SUCCESS = 'CREATE_DEDUCTION_SUCCESS'
export const CREATE_DEDUCTION_FAILURE = 'CREATE_DEDUCTION_FAILURE'

// ACTION POSITION
export const GET_POSITION_REQUEST = 'GET_POSITION_REQUEST'
export const GET_POSITION_SUCCESS = 'GET_POSITION_SUCCESS'
export const GET_POSITION_FAILURE = 'GET_POSITION_FAILURE'

export const CREATE_POSITION_REQUEST = 'CREATE_POSITION_REQUEST'
export const CREATE_POSITION_SUCCESS = 'CREATE_POSITION_SUCCESS'
export const CREATE_POSITION_FAILURE = 'CREATE_POSITION_FAILURE'

// ACTION RECAP
export const LIST_RECAP_REQUEST = 'LIST_RECAP_REQUEST'
export const LIST_RECAP_SUCCESS = 'LIST_RECAP_SUCCESS'
export const LIST_RECAP_FAILURE = 'LIST_RECAP_FAILURE'

export const EXPORT_RECAP_REQUEST = 'EXPORT_RECAP_REQUEST'
export const EXPORT_RECAP_SUCCESS = 'EXPORT_RECAP_SUCCESS'
export const EXPORT_RECAP_FAILURE = 'EXPORT_RECAP_FAILURE'

export const DETAIL_RECAP_REQUEST = 'DETAIL_RECAP_REQUEST'
export const DETAIL_RECAP_SUCCESS = 'DETAIL_RECAP_SUCCESS'
export const DETAIL_RECAP_FAILURE = 'DETAIL_RECAP_FAILURE'

export const HISTORY_RECAP_REQUEST = 'HISTORY_RECAP_REQUEST'
export const HISTORY_RECAP_SUCCESS = 'HISTORY_RECAP_SUCCESS'
export const HISTORY_RECAP_FAILURE = 'HISTORY_RECAP_FAILURE'

export const EMPLOYEE_RECAP_REQUEST = 'EMPLOYEE_RECAP_REQUEST'
export const EMPLOYEE_RECAP_SUCCESS = 'EMPLOYEE_RECAP_SUCCESS'
export const EMPLOYEE_RECAP_FAILURE = 'EMPLOYEE_RECAP_FAILURE'