export const SET_SITE_THEME = 'SET_SITE_THEME'

export const AUTHENTICATE_USER_REQUEST = 'AUTHENTICATE_USER_REQUEST'
export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS'
export const AUTHENTICATE_USER_FAILURE = 'AUTHENTICATE_USER_FAILURE'
export const UPDATE_AUTH_CURRENT_USER = 'UPDATE_AUTH_CURRENT_USER'

export const LOGO_COMPANY_REQUEST = 'LOGO_COMPANY_REQUEST'
export const LOGO_COMPANY_SUCCESS = 'LOGO_COMPANY_SUCCESS'
export const LOGO_COMPANY_FAILURE = 'LOGO_COMPANY_FAILURE'
