export const SET_SITE_THEME = 'SET_SITE_THEME'

export const AUTHENTICATE_USER_REQUEST = 'AUTHENTICATE_USER_REQUEST'
export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS'
export const AUTHENTICATE_USER_FAILURE = 'AUTHENTICATE_USER_FAILURE'
export const UPDATE_AUTH_CURRENT_USER = 'UPDATE_AUTH_CURRENT_USER'

export const LOGO_COMPANY_REQUEST = 'LOGO_COMPANY_REQUEST'
export const LOGO_COMPANY_SUCCESS = 'LOGO_COMPANY_SUCCESS'
export const LOGO_COMPANY_FAILURE = 'LOGO_COMPANY_FAILURE'

// ACTION PROFILE
export const FORGOT_PASS_REQUEST = 'FORGOT_PASS_REQUEST'
export const FORGOT_PASS_SUCCESS = 'FORGOT_PASS_SUCCESS'
export const FORGOT_PASS_FAILURE = 'FORGOT_PASS_FAILURE'

// ACTION PRICE
export const IMPORT_PRICE_REQUEST = 'IMPORT_PRICE_REQUEST'
export const IMPORT_PRICE_SUCCESS = 'IMPORT_PRICE_SUCCESS'
export const IMPORT_PRICE_FAILURE = 'IMPORT_PRICE_FAILURE'

export const EXPORT_PRICE_REQUEST = 'EXPORT_PRICE_REQUEST'
export const EXPORT_PRICE_SUCCESS = 'EXPORT_PRICE_SUCCESS'
export const EXPORT_PRICE_FAILURE = 'EXPORT_PRICE_FAILURE'

export const EDIT_PRICE_REQUEST = 'EDIT_PRICE_REQUEST'
export const EDIT_PRICE_SUCCESS = 'EDIT_PRICE_SUCCESS'
export const EDIT_PRICE_FAILURE = 'EDIT_PRICE_FAILURE'

